### ISSUE TITLE
Transform into charm

### ISSUE THREAD

**Issue by jakobilobi** [dwellir-public/endpointdb#14]
Making the `endpointdb` app a charm would increase ease of usage and enable usage of relations to other applications (e.g. the `blockchain-monitor`) in our infrastructure.

When charmified, the repo should probably be renamed `endpointdb-operator`.

**Comment by jakobilobi** [comment]
Started working on this during my Internet outage this morning. Goal is to first make a working charm with an easy deploy process, then to incorporate the `self.unit.open_port()` functionality included in the newer `ops` versions. At least if that seems needed to make the API callable remotely, will have to test first!

**Comment by erik78se** [comment]
You can implement the http interface as a relation, which then would allow
us to relate to haproxy automatically.

But it might be overkill

Den mån 10 juli 2023 11:34Jakob ***@***.***> skrev:

**Comment by jakobilobi** [comment]
> You can implement the http interface as a relation, which then would allow us to relate to haproxy automatically.

We want to relate this to `haproxy`?

The port-opening-code I was thinking would be to make AWS automatically open the Flask API port for the container if deployed to AWS.

**Comment by erik78se** [comment]
It might be easier to add tls to the service, but it can possibly be added
some other way....

Den tis 11 juli 2023 16:53Jakob ***@***.***> skrev:

**Comment by jakobilobi** [comment]
Done with https://github.com/dwellir-public/endpointdb/pull/17
