### ISSUE TITLE
Capture urls that isn't working properly

### ISSUE THREAD

**Issue by erik78se** [dwellir-public/endpointdb#6]
As of now, we can't figure out which URL:s are not working. E.g. don't respond to query or returns bogus data etc.

We need to be able to discover this in the update cycles.

**Comment by jakobilobi** [comment]
I'd say this is somewhat solved, so I'll close the issue for now:

Can be seen in the log of the [blockchain-monitor charm](https://github.com/[dwellir-public/blockchain-monitor](https://github.com/dwellir-public/blockchain-monitor)), and can be tested by running the `db_util.py json` validation.
